### ISSUE TITLE
error installing dependencies when installing setlr

### ISSUE THREAD

**Issue by rashidsabbir** [tetherless-world/setlr#16]
Error results when attempting to install setlr where the dependencies do not get installed automatically.

```Collecting setlr
  Using cached setlr-1.0.0.tar.gz (22 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ro55lfbv/setlr_445af19a28c44e96bb4e2f398cfe8be3/setup.py", line 3, in <module>
          from setlr._version import __version__
        File "/tmp/pip-install-ro55lfbv/setlr_445af19a28c44e96bb4e2f398cfe8be3/setlr/__init__.py", line 7, in <module>
          from rdflib import *
      ModuleNotFoundError: No module named 'rdflib'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by jpmccu** [comment]
rdflib is currently one of the dependencies for SETLr, so it's not clear what conditions are triggering this failure. Please retest and provide the command sequence that produces this condition.
